### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by zmm96** [geekyutao/GraphIQA#1]
In pretraining,  The dataset you used is Kondid-10k or Kondis-700k?
you mean  pretraining GraphIQA model from scratch on kadid10k dataset but the code seems only Kondis-700k?

**Comment by sunsm-2020** [comment]
The model can be pre-trained on both kadid-10k and kadis-700k from scratch by running 'python pretrain.py --dataset kadid-P' and 'python pretrain.py --dataset kadis-P' correspondingly.
