### ISSUE TITLE
Enquire about the database splitting - 60% training, 20% validation, and 20% testing

### ISSUE THREAD

**Issue by SuperBruceJia** [geekyutao/GraphIQA#3]
Dear,

Thanks a lot for your great work!

Could you **share your experimental results (SRCC and PLCC)** (Database: LIVE, CSIQ, TID2013, and KADID-10k) by **splitting the dataset into 60% training, 20% validation, and 20% testing**?

Thanks in advance and have a nice day!

Best,

Shuyue
Feb 8, 2022

**Comment by sunsm-2020** [comment]
The experimental results are as follows:
LIVE: SRCC 0.9684 PLCC 0.9704
CSIQ: SRCC 0.9203 PLCC 0.9376
KADID-10k: SRCC 0.8846 PLCC 0.8840
